### ISSUE TITLE
Initial Create Class / Value Set Feedback

### ISSUE THREAD

**Issue by dylanvaughn** [metadatacenter/cedar-template-editor#115]
1. The ontology tree is not centered on the term that is being selected.
2. The right part of the ontology tree is not visualized correctly. This is a problem when the user goes deep in the ontology hierarchy (see 1.png).
3. When opening the modal and selecting either Field or Values, it is not possible to go back and change the selection. For instance, after clicking on Field, there is now way of going back and select Values. The user is forced to close the modal and start again.
4. Rendering of 'value constrained' field: I added two values (skin cancer and lung cancer to a 'disease' field). The representation of the field is wrong: see 2.png.
5. Class creation. The visual representation of the mapping could be improved. It would be nice to show an arrow from term1 to term2, as specified in our wireframes. Also, the alignment of the button has to be corrected. See 3.png.
6. When browsing the CEDARVS ontology, all value sets created from the template editor should be there. You can use the following operation of the terminology server to show all value sets in a value set collection, including the recently created ones: GET /bioportal/vs-collections/{vs_collection}/value-sets.
7. When browsing the CEDARPC ontology, all classes created from the template editor should be there. Now, a message  "No submissions available is shown" (see 4.png). There is a specific endpoint to retrieve all provisional classes from a specific ontology in the Terminology Server (GET /bioportal/ontologies/{ontology}/classes/provisional). However, I have just seen that it is returning an error. We need to fix it. Meanwhile you can retrieve all provisional classes using 'GET /bioportal/classes/provisional' and show only the ones for the CEDARPC ontology.
8. When creating a value set, the Label and Description fields are represented as required but the validation is not working. I was able to create a value set with no label, description and values (see 5.png). Something similar is happening for class creation.

https://basecamp.com/1771528/projects/9018044/messages/55508660

**Comment by marcosmartinezromero** [comment]
Number 2 is related to #12

**Comment by acarlton** [comment]
Hello @marcosmartinezromero,

I am noticing from my testing for #7, that the call to:

GET https://data.bioontology.org/ontologies/CEDARPC/latest_submission

is returning an empty JSON hash, {}. Is this expected behavior? Perhaps I am doing something wrong, but I have verified it in Chrome's network inspector and Postman. Please advise as this call drives our tree creation logic.

**Comment by marcosmartinezromero** [comment]
Hi @acarlton,

Yes, that it the expected behavior. The CEDARPC ontology does not contain any 'regular' class. It only contains 'provisional' classes. BioPortal submissions only contain regular classes. That is why the call to .../latest_submision is returning an empty JSON object.

The following call:

GET https://terminology.metadatacenter.net/bioportal/ontologies/CEDARPC

should return both all regular and provisional classes, but it is not working now. This could be related to the issue that I mentioned in my previous message (number 7). I will need to fix that. As a temporary solution, you can use the following call to retrieve all provisional classes:

GET https://terminology.metadatacenter.net/bioportal/classes/provisional

And then filter the results to keep only those with: 

"ontology": "http://data.bioontology.org/ontologies/CEDARPC"

Regarding number 6, I just tested the following call to obtain all value sets in the CEDARVS collection:

GET https://terminology.metadatacenter.net/bioportal/vs-collections/CEDARVS/value-sets

and it is working fine for me. Please, try to make this call again to see if you are still receiving an error.

After listing all value sets in CEDARVS, you can use the following call to get all values in a particular value set:

GET /bioportal/vs-collections/{vs_collection}/value-sets/{vs}/values

Example: get all values in the value set: 'http://data.bioontology.org/provisional_classes/8d4a8b20-c92e-0133-b24f-005056010074':

https://terminology.metadatacenter.net/bioportal/vs-collections/CEDARVS/value-sets/http%3A%2F%2Fdata.bioontology.org%2Fprovisional_classes%2F8d4a8b20-c92e-0133-b24f-005056010074/values

You could use these calls for the value sets, instead of displaying them using the BioPortal API. Does this make sense for you?

Marcos

**Comment by martinjoconnor** [comment]
@marcosmartinezromero  will tackle numbers 6 (#142) and 7 (#147) so this is now closed.
