### ISSUE TITLE
Cannot delete multiple instance fields or elments  in template or element editors

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#316]
In some cases these delete button becomes inactive in multiple instance fields in the template editor - so the field cannot be deleted.

Not clear how to reproduce. Was observed on multiple-instance phone and text fields.

It seems that some combination of the min and max fields causes the delete icon to become disabled for the field.

**Comment by willrett** [comment]
can't duplicate, but maybe because the ids were all the same

**Comment by martinjoconnor** [comment]
When minimum cardinality is set to 0 it breaks.  Seems to work otherwise.

**Comment by willrett** [comment]
code for this fix was reverted

**Comment by proccaserra** [comment]
if of any help, I observed the following:
I deleted an element which is used by a template. by pressing the 'bin' button, the element (hardware in my case) is deleted but then trigger the following:

Technical details of error

Status: -1, 
URL: https://resource.metadatacenter.net/template-elements/https%3A%2F%2Frepo.metadatacenter.net%2Ftemplate-elements%2Fa438e305-055e-4e64-bbda-37467209ee0f/details
Method: GET

Message: 
Exception: 

Stack trace:

----
probably caused by the fact that page is not refreshed but still links to the element just deleted.

so refreshing the page drops the 'hardware' element from the list. I then select the 'instrument' template which uses the 'hardware' element (which have been deleted). I can still use the template and populate it.

How comes it is possible to delete an element when in use by other entities?
