### ISSUE TITLE
Can't access Gazetteer ontology

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-template-editor#348]
When selecting a new ontology class, ending up at Gazetteer ontology produces system error. Can search for 'city' in class and select a 'City of ...' entry (far down the list), or 'Gaz' in ontologies. System stops at that point. If you wait long enough, you might get the display enclosed.
![screen shot 2016-06-24 at 7 48 13 am](https://cloud.githubusercontent.com/assets/1266896/16341143/8494d050-39e0-11e6-8797-e9733c0f9c2d.png)

**Comment by marcosmartinezromero** [comment]
This seems to be a BioPortal issue. The BioPortal endpoint to retrieve the roots of the Gazetteer ontology (http://data.bioontology.org/ontologies/GAZ/classes/roots) is returning a timeout. This issue is reflected in the BioPortal UI too: http://bioportal.bioontology.org/ontologies/GAZ/?p=classes&conceptid=root

**Comment by martinjoconnor** [comment]
As per #338, we should probably think of handling these timeout issues with a dialog. The problem is deciding what that timeout should be.

**Comment by marcosmartinezromero** [comment]
In this case, the Terminology Server is receiving a timeout from BioPortal but returning an internal error to the UI, so we could show a dialog for it

**Comment by marcosmartinezromero** [comment]
Given the low number of flat ontologies in BioPortal (13, 2.5%), for the moment CEDAR has implemented the same approach than BioPortal and it does not support tree browsing for flat ontologies. Now CEDAR shows the message "Tree browsing not supported for this ontology" for flat ontologies instead of returning an Internal Server Error. 
If the user searches for a class that belongs to a flat ontology, the ontology tree will not be shown but all the information for the class will be retrieved and correctly displayed.
