### ISSUE TITLE
Can not enter metadata

### ISSUE THREAD

**Issue by ahmadchan** [metadatacenter/cedar-template-editor#675]
When I enter metadata into any field in AIRR template. System says "No result" (I think, system tries to find a match from ontology) and by pressing the OK button, it jumps to the next field keeping the previous field empty. Please see the attachment
![cannot](https://user-images.githubusercontent.com/1532039/28139916-17424cb8-6724-11e7-82c8-3d15cb667650.png)

**Comment by martinjoconnor** [comment]
We discovered that this was because the value of a field was restricted to a single ontology term. (The gibberish above the field value has now been removed.)

However, @ahmadchan still seems to have issues with this field even after removing this restriction. Can you send a link to an instance showing a case where you cannot enter metatata.

**Comment by ahmadchan** [comment]
Here is the link of instance https://cedar.staging.metadatacenter.net/instances/create/https://repo.staging.metadatacenter.net/templates/eb8c610c-c4d1-4687-80bb-b980a9fdb9d7?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2F51efb614-a148-49ee-83f8-b86fe87ede55. Try to enter study id
