### ISSUE TITLE
Default for controlled term  fields

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#685]
Currently default values only work for string fields. Need to have defaults for other field types too.

**Comment by agbeltran** [comment]
@martinjoconnor would this issue about default/hidden values for URI cover the case where one wants to point to a populated template as the default value for a field?

I would think so, as I see that populated templates are assigned an '@id' but I wonder if this URI can be accessed from a template so that the default value can be defined. 

A use case for this would be to have a template for provenance information of other templates (so the latter can point to a populated template).

**Comment by martinjoconnor** [comment]
See also: https://github.com/metadatacenter/cedar-template-editor/issues/60

**Comment by martinjoconnor** [comment]
Relevant for CDE work.

**Comment by willrett** [comment]
Added.

**Comment by johardi** [comment]
I reopen the issue because the produced defaultValue object doesn't comply with the meta-model. The structure for the object should be as follows:
```
"defaultValue": {
   "type": "Value" or "OntologyClass",
   "termUri": "http://...",
   "sourceUri": "http://..."
}
```

instead of:
```
"defaultValue": {
   "termUri": "http://...",
   "rdfs:label": "..."
}
```

**Comment by johardi** [comment]
Nevermind-- The structure from the editor is the correct one
